a=int(input("enter your name"))
b=int(input("enter your name"))
c=int(input("enter your name"))
print("addition : ",a+b)
print("subtraction : ",a-b)
print("mul : ",a*b)
print("division : ",a/b)
print("floor division : ",a//b)
print("modulas : ",a%b)
print("power : ",a**b)
print("cupe : ",a**3)
print("average : ",a+b+c/3)
print(a>=b and a==b)
print(id(a))
integer=15
float=7.5
print(integer+float)
print(a>=b)
print(a==b)
print(a+b+c/3)
